[#ai-library-installing]
include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
endif::[]
ifndef::override-title[]
= Installing applications from {ailibrary}
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
{productname} is delivered as a set of components that you can combine to meet specific use cases.
To enable the full integrated stack, you need to deploy multiple applications in sequence.
Applications with the fewest dependencies must be installed first, followed by dependent applications once their required dependencies are in place within the cluster.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

include::../snippets/ai-separate-rancher-cluster.adoc[]

[#ai-library-whatis-sappco]
== What is {sappco}?
{sappco} provides curated, trusted, compliant and up-to-date applications for {kube}.
Learn more on its dedicated link:https://apps.rancher.io/[Web site] and in the link:https://www.suse.com/products/rancher/application-collection/[product summary].

[#ai-library-whatis-sregistry]
== What is {sregistry}?
Applications in the {sregistry} are not built by the {suse} build system.
They are mirrored upstream projects with attached supply chain artifacts.
These artifacts help you source popular applications and tools in the AI ecosystem from a single source and provide built-in visibility into their upstream origins.
Learn more on the registry's link:https://registry.suse.com/[Web site]
ifeval::["{PROF_DEPLOYMENT}" == "standard"]
and refer to xref:ai-library-apps-verifying[] to see how to verify the supply chain artifacts
endif::[]
.

ifeval::["{PROF_DEPLOYMENT}" == "standard"]
You can install the required {ailibrary} component {helm} charts using one of the following methods:

* Use {saifactory} to install AI applications _blueprints_.
  Refer to link:https://documentation.suse.com/suse-ai-factory/latest/[{saifactory} documentation] for more details.
* Install each AI application manually using the {helm} CLI as described in xref:suse-ai-deploy-suse-ai[].
//* Use a meta {helm} chart called {saideployer} to include all the dependencies specific to your use case.
//  Refer to xref:ailibrary-installing-deployer[] for more details.
endif::[]