include::../common/generic-attributes.adoc[]
// overridden title?
ifdef::override-title[]
= {override-title}
endif::[]
ifndef::override-title[]
= GPU hardware for AI/ML workloads
endif::[]
// overridden abstract?
ifdef::override-abstract[]
{override-abstract}
endif::[]
ifndef::override-abstract[]
To run AI/ML workloads, such as training machine learning models or running inference workloads, deploy cluster nodes with compatible {nvidia} GPUs to gain acceleration.
endif::[]

// erase the flag for future overrides
:override-abstract!:
:override-title!:

:revdate: 2026-06-29
:page-revdate: {revdate}

[#ai-reqs-hw-gpu-operator]
== Using the {nvoperator}

Configuring and managing nodes with hardware resources can require multiple configurations for software components.
These include drivers, container runtimes and libraries.
To use {nvidia} GPUs in a {kube} cluster, you need to configure the {nvoperator}.
Because GPU is a special resource in the cluster, you need to install the following components to enable deployment of workloads for processing on the GPU.

* {nvidia} drivers (to enable CUDA)
* {kube} device plug-in
* Container runtime
* Other tools to provide capabilities such as monitoring or automatic node labeling

To ensure that the {nvoperator} is installed correctly, the {kube} cluster must meet the following prerequisites:

* All worker nodes must run the same operating system version to use the {nvidia} GPU Driver container.
* Nodes must be configured with a container engine, such as {docker} (CE/EE), {containerd} or {podman}.
* Nodes should be equipped with {nvidia} GPUs.
* Nodes should have {nvidia} drivers installed.

[#ai-reqs-hw-supported-gpus]
== Recommended and supported GPUs

We highly recommend one or more GPUs with ample of VRAM for the worker nodes.
The required number of GPUs and the VRAM capacity per GPU depend mainly on the size of the AI model that your workload uses.
Furthermore, for high availability (HA) deployments, we recommend all the worker nodes to have the same GPU configuration so that PODs can be rescheduled when necessary.

For a full list of supported GPUs, refer to the https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/platform-support.html[{nvoperator} Platform Support] documentation.
